#8393 講座資料のブラッシュアップ
TORIFUKUKaiou/linebot-sample-ruby pull request #1
Opened 2023-02-05 09:19 UTC by IshimotoTakara

Rubyの環境構築から、LINEBotの設定、ローカルで動かすまでの手順を丁寧に説明してるかと思います。
WindowsPCを持っていないので、参考記事を添付しています。

2023-02-06 05:51 UTC, TORIFUKUKaiou requested changes
- [Must] Dockerの手順は、そのまま(Windowsの手順の前くらいに)残しておいてください。
- `.env`は環境変数と`=`のあいだに空白があっても大丈夫なものですか？
- 誤記? の提案をしました

2023-02-06 05:51 UTC, TORIFUKUKaiou commented on .env
> +LINE_CHANNEL_TOKEN =
```suggestion
LINE_CHANNEL_ID=
LINE_CHANNEL_SECRET=
LINE_CHANNEL_TOKEN=
```

spaceがあるとだめな気がします。違いますかね。

2023-02-06 05:51 UTC, TORIFUKUKaiou commented on README.md
> +一派的にrubyはrbenvで管理する方法が知られています。
```suggestion
一般的にrubyはrbenvで管理する方法が知られています。 
```

2023-02-06 05:51 UTC, TORIFUKUKaiou commented on README.md
> -# [Docker](https://www.docker.com/) + [Ngrok](https://ngrok.com/) で動かす
[must] Dockerで動かす手順は全部消さずにそのまま残しておいてください。

2023-02-06 05:51 UTC, TORIFUKUKaiou commented on README.md
> +LINE_CHANNEL_TOKEN = [先ほど発行したチャネルアクセストークン]
```suggestion
LINE_CHANNEL_ID=[チャネル基本設定/基本情報/チャネルID]
LINE_CHANNEL_SECRET=[チャネル基本設定/基本情報/チャネルシークレット]
LINE_CHANNEL_TOKEN=[先ほど発行したチャネルアクセストークン]
```

=の前後にスペースがあると駄目なんじゃないかという気がしますが、そんなことはないですか。

2023-02-06 15:30 UTC, IshimotoTakara commented on .env
> +LINE_CHANNEL_TOKEN =
ダメではないみたい（動きました）でしたけど、詰めて書いてるのが良いですかね？

2023-02-07 12:56 UTC, TORIFUKUKaiou requested changes
あと3箇所よろしくお願いします。

2023-02-07 12:56 UTC, TORIFUKUKaiou commented on README.md
> +LINE_CHANNEL_TOKEN = [先ほど発行したチャネルアクセストークン]
[must]
.env は、スペースあってもよいことはわかりました。READMEと.envで2通り存在しているので、こちらのスペースを消してもらえますでしょうか。

2023-02-07 12:56 UTC, TORIFUKUKaiou commented on README.md
> +
[must]
ここに .env を書き換える手順をいれてください。
.envを使う手順で統一しましょう。

2023-02-07 12:56 UTC, TORIFUKUKaiou commented on README.md
> +docker run -d -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e LINE_CHANNEL_ID="165...yours" -e LINE_CHANNEL_SECRET="82a...yours" -e LINE_CHANNEL_TOKEN="wTq+...yours" -p 4567:4567 my-linebot-ruby-app
[must]
```suggestion
docker run -d -v "$PWD":/usr/src/myapp -w /usr/src/myapp -p 4567:4567 my-linebot-ruby-app
```

docker run では環境変数は指定しないことにします。

2023-02-09 21:05 UTC, TORIFUKUKaiou requested changes
コメントしました。

2023-02-09 21:05 UTC, TORIFUKUKaiou commented on README.md
> +# Installing / Getting started
```suggestion
# Installing / Getting started

まずmacOSでの構築手順を示します。  
Windowsの方は後述の手順をご確認ください。  



```

2023-02-09 21:05 UTC, TORIFUKUKaiou commented on README.md
> +![全体像](https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F552343%2F13ab399f-3ece-7963-d614-b13deb4bb7c7.png?ixlib=rb-4.0.0&auto=format&gif-q=6
この絵は石本くんが書いたものではなかったりしますか、もしかして。

修正できるようしたらお願いしたいです。
また他の人の記事の画像であれば、記事のリンクを画像の下に書いておいてください。

https://camo.githubusercontent.com/8c5a450466e0d69d6fb08115f133f3758019775e1a017b855e1823e668db35a5/68747470733a2f2f71696974612d757365722d636f6e74656e74732e696d6769782e6e65742f687474707325334125324625324671696974612d696d6167652d73746f72652e73332e61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2532463025324635353233343325324631336162333939662d336563652d373936332d643631342d6231336465623462623763372e706e673f69786c69623d72622d342e302e30266175746f3d666f726d6174266769662d713d363026713d373526773d31343030266669743d6d617826733d6635663332343138663938313633353638633133636163643865363961616137

雲がNgrokかな。
以下のようにしていただけますでしょうか。

- 一番左の「おはよう」の線の色を赤(見やすいセンスのいい色でよいです)
- LINEサーバー -> Ngrok -> Local PCの線の色を赤(見やすいセンスのいい色でよいです)
- Local PC -> LINEサーバ(Response) -> スマホの線の色を青(見やすいセンスのいい色でよいです)


Responseの←は、 LINEサーバ ← Local PCを直接結んでください。
戻りはngrokを経由しないはずです。
https://developers.line.biz/ja/reference/messaging-api/#send-reply-message
私が勘違いしているようでしたらコメントください。

2023-02-16 17:20 UTC, TORIFUKUKaiou commented on README.md
> +![全体像](https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F552343%2F13ab399f-3ece-7963-d614-b13deb4bb7c7.png?ixlib=rb-4.0.0&auto=format&gif-q=6
[Must]
https://github.com/IshimotoTakara/linebot-sample-ruby/tree/d44ddab41db743f4ad30d0256366ea0c95fb1afb

![スクリーンショット 2023-02-17 2 17 47](https://user-images.githubusercontent.com/4215723/219439953-0cdb2061-a2a2-4257-baa2-515c9c944da5.png)

文字の位置がちょっとおかしいです。

たぶん、
```suggestion
![全体像](https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F552343%2F13ab399f-3ece-7963-d614-b13deb4bb7c7.png?ixlib=rb-4.0.0&auto=format&gif-q=60&q=75&w=1400&fit=max&s=f5f32418f98163568c13cacd8e69aaa7)  
```

空白を２つ入れるといけるんじゃないかな。

2023-02-16 17:22 UTC, TORIFUKUKaiou approved these changes

2023-02-16 17:22 UTC, merged

2023-02-16 17:25 UTC, TORIFUKUKaiou commented on README.md
> +![全体像](https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F552343%2F13ab399f-3ece-7963-d614-b13deb4bb7c7.png?ixlib=rb-4.0.0&auto=format&gif-q=6
うしろにスペース2がつないと表示がちょっと変でした。私のほうで対応しておきました。

![スクリーンショット 2023-02-17 2 17 47](https://user-images.githubusercontent.com/4215723/219441354-8d95c58f-6881-4f5a-a88a-5206f0128ff8.png)

2023-02-16 17:27 UTC, IshimotoTakara commented on README.md
> +![全体像](https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F552343%2F13ab399f-3ece-7963-d614-b13deb4bb7c7.png?ixlib=rb-4.0.0&auto=format&gif-q=6
ありがとうございます！自分の方ではたまたま改行された風になっていたので、気づきませんでした😓